version: "3.9"

services:
  db:
    image: postgres:14.2-bullseye
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "api"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"

  api:
    volumes:
      - ./api:/api

    ports:
      - "8000:8000"

    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "api"
      DJANGO_SECRET_KEY: "django-insecure-ta+%zrwt!v3@bn^vlsddo2d6sqcyd&m8m2!hqh$$)9#sh323ake"
      DJANGO_ENVIRONMENT: "Development"

    depends_on:
      - db
      - crawler

  crawler:
    volumes:
      - ./api:/api
      - ./crawler:/crawler

    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "api"
      DJANGO_SECRET_KEY: "django-insecure-ta+%zrwt!v3@bn^vlsddo2d6sqcyd&m8m2!hqh$$)9#sh323ake"
      DJANGO_SETTINGS_MODULE: "api.settings"

    depends_on:
      - db
