version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile

    command: sh -c "python manage.py migrate &&
      python price_historic_saver.py &
      python manage.py runserver 0.0.0.0:8000 --noreload"

    ports:
      - "8000:8000"

  crawler:
    build:
      context: .
      dockerfile: ./crawler/Dockerfile

    command: sh -c "python worker.py"
