# Generated by Django 4.0.4 on 2022-05-12 01:27

# noinspection PyUnresolvedReferences
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_username_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=254, unique=True)),
                ('score', models.IntegerField(null=True)),
                ('epic_price', models.DecimalField(
                    decimal_places=2, max_digits=5, null=True
                )),
                ('gog_price', models.DecimalField(
                    decimal_places=2, max_digits=5, null=True
                )),
                ('green_man_price', models.DecimalField(
                    decimal_places=2, max_digits=5, null=True
                )),
                ('microsoft_price', models.DecimalField(
                    decimal_places=2, max_digits=5, null=True
                )),
                ('nuuvem_price', models.DecimalField(
                    decimal_places=2, max_digits=5, null=True
                )),
                ('origin_price', models.DecimalField(
                    decimal_places=2, max_digits=5, null=True
                )),
                ('rockstar_price', models.DecimalField(
                    decimal_places=2, max_digits=5, null=True
                )),
                ('steam_price', models.DecimalField(
                    decimal_places=2, max_digits=5, null=True
                )),
                ('ubisoft_price', models.DecimalField(
                    decimal_places=2, max_digits=5, null=True
                )),
                ('image', models.ImageField(
                    null=True, upload_to=core.models.game_image_path
                )),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
    ]
