# Generated by Django 4.0.4 on 2022-05-15 17:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_gamemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('image', models.ImageField(
                    null=True,
                    upload_to=core.models.get_image_path
                )),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='epic_price',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='gog_price',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='green_man_price',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='microsoft_price',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='nuuvem_price',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='origin_price',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='rockstar_price',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='steam_price',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='ubisoft_price',
        ),
    ]
