# Generated by Django 4.0.4 on 2022-05-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_wishlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='link',
            field=models.URLField(
                default='https://<django.db.models.fields.CharField>.com/',
                unique=True),
        ),
    ]
