# Generated by Django 4.0.4 on 2022-05-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_storemodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
