# Generated by Django 4.0.4 on 2022-05-19 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_alter_storemodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistoricmodel',
            name='time_saved',
            field=models.DateField(default=datetime.date.today,
                                   unique_for_date='game'),
        ),
    ]
