# Generated by Django 4.0.5 on 2022-06-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_storemodel_options_alter_storemodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemodel',
            name='link',
            field=models.URLField(default='https://example.com/'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
