# Generated by Django 4.0.5 on 2022-07-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pricemodel_link_alter_storemodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
